version: "2"
services:
    client:
        build: client
        image: webapp-client
        restart: always
        ports:
            - 3000:3000
        links:
            - api
        networks:
            - webappnetwork
        stdin_open: true
        volumes:
            - ./client:/client
    api:
        build: ./api
        image: webapp-api
        restart: always
        ports:
            - 5000:5000
        networks:
            - webappnetwork
        command: python3 api.py
        volumes:
            - ./api:/api
networks:
    webappnetwork:
        driver: bridge
